name: firstapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  google_gemini: ^0.1.2
  http: ^1.1.2
  flutter_markdown: ^0.7.7+1
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^ 5.6.7
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
     - lib/images/
